---
title: "Testing"
author: "Roger Bivand"
date: "16/6/2020"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Testing linegraph morphing

```{r}
# packages
library(sf)
library(sfnetworks)
library(spdep)
library(tidygraph)
library(igraph)
library(dplyr)

# data
network_column <- st_sfc(
  st_linestring(matrix(c(0, -2, 0, -1, 0, 0), ncol = 2, byrow = TRUE)), 
  st_linestring(matrix(c(0, 2, 0, 1, 0, 0), ncol = 2, byrow = TRUE)), 
  st_linestring(matrix(c(-2, 0, -1, 0, 0, 0), ncol = 2, byrow = TRUE)), 
  st_linestring(matrix(c(2, 0, 1, 0, 0, 0), ncol = 2, byrow = TRUE)), 
  st_linestring(matrix(c(2, -2, 2, -1, 2, 0), ncol = 2, byrow = TRUE)),
  st_linestring(matrix(c(2, 2, 2, 1, 2, 0), ncol = 2, byrow = TRUE)), 
  st_linestring(matrix(c(2, 0, 3, 0, 4, 0), ncol = 2, byrow = TRUE))
)


# assign some random measurements to all edges
set.seed(1)
network_data <- st_as_sf(
  data.frame(x = runif(7)), 
  geometry = network_column
)

# plot
plot(st_geometry(network_data))

# create sfnetwork structure
sfnetwork_data = as_sfnetwork(network_data, directed = FALSE)

# plot the sfnetwork object
plot(sfnetwork_data)

# create the line graph
# sfnetwork_data %>% convert(to_linegraph)

dual = sfnetwork_data %N>% convert(to_linegraph)
dual

# build adj matrix for the edges
am <- as_adjacency_matrix(dual)
am

am_list <- mat2listw(am, style = "B")
am_list

val <- sfnetwork_data %>% activate(edges) %>% pull(x)

my_moran <- moran(x = val, listw = am_list, n = ecount(sfnetwork_data), S0 = Szero(am_list))
my_moran

estimate_my_moran <- function(sfnetwork_object, val) {
  # 1. Create the dual graph / linegraph
  sfnetwork_object_dual <- sfnetwork_object %>%
    convert(to_linegraph)
  
  # 2. Estimate adj matrix
  edge_adj <- as_adjacency_matrix(sfnetwork_object_dual)
  
  # 3. Convert to list2format
  edge_listw <- mat2listw(edge_adj)
  
  # 4. extract the data
  x <- sfnetwork_object %>% activate(edges) %>% pull({{val}})
  
  # 5. Estimate moran's I
  moran(x, edge_listw, ecount(sfnetwork_object), Szero(edge_listw))
}

estimate_my_moran(sfnetwork_data, x)
```

